import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";


export const metadata = {
  title: "DriveNFind",
  description: "Generated by create next app",
  icons: {
    icon:'/LogoDriveNFind.png',
  }
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          {children}
        </body>
      </html> 
    </ClerkProvider>
  );
}
